# Generated by Django 4.2.6 on 2023-11-05 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branch',
            name='items',
            field=models.ManyToManyField(blank=True, related_name='seller', to='tracker.item'),
        ),
    ]
