# Generated by Django 4.2.6 on 2023-11-04 19:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchaseHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('travel_expense', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('nickname', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PurchaseItems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.RenameField(
            model_name='item',
            old_name='price',
            new_name='weight',
        ),
        migrations.RemoveField(
            model_name='branch',
            name='costs',
        ),
        migrations.RemoveField(
            model_name='grocerystore',
            name='branch',
        ),
        migrations.RemoveField(
            model_name='item',
            name='grocery_store',
        ),
        migrations.AddField(
            model_name='branch',
            name='grocery_store',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='branches', to='tracker.grocerystore'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='branch',
            name='items',
            field=models.ManyToManyField(related_name='branches', to='tracker.item'),
        ),
        migrations.DeleteModel(
            name='Purchase',
        ),
        migrations.AddField(
            model_name='purchaseitems',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tracker.item'),
        ),
        migrations.AddField(
            model_name='purchaseitems',
            name='purchase',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itemsPurchased', to='tracker.purchasehistory'),
        ),
        migrations.AddField(
            model_name='purchasehistory',
            name='grocery_store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchases', to='tracker.branch'),
        ),
    ]
