# Generated by Django 4.2.6 on 2023-11-05 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0002_purchasehistory_purchaseitems_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branch',
            name='items',
            field=models.ManyToManyField(blank=True, related_name='branches', to='tracker.item'),
        ),
    ]
