# Generated by Django 4.2.6 on 2023-11-06 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0002_alter_branch_items'),
    ]

    operations = [
        migrations.AddField(
            model_name='branch',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='branch_images/'),
        ),
        migrations.AddField(
            model_name='grocerystore',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='grocery_store_images/'),
        ),
    ]
